### PR TITLE
Feat: adds enums to Invoice and Invoice_Item models

### LINKED ISSUE #15: add status enums to invoice_items and invoices
We gotta incorporate the enums to invoice_items and invoices

Link on enums from Zanna: https://blog.saeloun.com/2022/01/05/how-to-use-enums-in-rails/

Invoice Status Options
* in progress
* completed
* cancelled

Invoice Items Status Options
* pending
* packaged
* shipped

### PR DESCRIPTION
**Pull request by Daniel-Gallagher92**

### CODE REVIEW

**Review by ethanrossblack — APPROVED** [review]
Looks great. you just gotta fill out your favorite gif

**Review by z-fitch — APPROVED** [review]
looks good

**Review by ethanrossblack — CHANGES_REQUESTED** [review]
give us the gif

**Comment by JorjaF** [comment]
looks good

**Comment by Daniel-Gallagher92** [comment]
https://media.giphy.com/media/FdINNRy04wzemFDKDh/giphy.gif

**Review by JorjaF — APPROVED** [review]
looks good

**Review by ethanrossblack — APPROVED** [review]
thanks, looks good now

**Pull request merged**
